#!/bin/bash

# Run 'make re' command
make re

# Check if make command was successful
if [ $? -eq 0 ]; then
    # If make command was successful, run minishell
   ./philo
else
    # If make command failed, display an error message
    echo "Error: Make command failed."
fi

