#!/bin/bash

# Default value for use_make
use_make=true

if [ "$#" -gt 0 ]; then
	use_make=false
fi

# Function to run make if necessary
run_make() {
	if [ "$use_make" = true ]; then
		make re
		make_exit_status=$?
		if [ $make_exit_status -ne 0 ]; then
			echo "Error: Make command failed."
			exit $make_exit_status
		fi
	fi
}

# Run make
run_make

# Check if make command was successful
if [ $? -eq 0 ]; then
	echo "Make successful. Running program under valgrind..."
	# If make command was successful, run valgrind with suppression file
	# Include all argv using "$@"
	valgrind --tool=helgrind --history-level=approx ./philo "$@" # 
	#valgrind --leak-check=full --track-origins=yes --track-fds=yes --show-leak-kinds=all --error-limit=no ./philo "$@"
	# Check valgrind's exit status
	valgrind_exit_status=$?
	# Check if valgrind command was successful
	if [ $valgrind_exit_status -eq 0 ]; then
		echo "Valgrind completed without errors."
	else
		echo "Error: Valgrind reported errors."
		exit $valgrind_exit_status
	fi
fi

